In [9]:
import sys
sys.path.append("../src")

from datacleaning import clean_data, handle_datatypes, check_impossible_values

perguntar ao stor:

- nan em complaints assumir como 0?

In [2]:
import os
os.getcwd()

'c:\\Users\\laura\\Desktop\\ML II\\ml_project\\notebooks'

In [3]:
import pandas as pd

#IDS SALTAM NUMERO A FRENTE, O QUE FAZER , manter a numeracao que ja vem_

DETETAR OUTLIERS COM DBSCAN

In [4]:
#perceber bem o que é sobre o dataset

#IDS SALTAM NUMERO A FRENTE, O QUE FAZER , manter a numeracao que ja vem? ok, nao fazer isto pq tira a ligacao dos dois datasets ver istooooo

#ver as birthdates, maybe dar match das datas com o msc e bsc?

#OUTLIERS COM DBSCAN

#meter loyalty number binario

#adicionar validation rules talvez? ou explicar pelo menos???????

#tirar o bsc e o msc e criar uma coluna com isso


# requirements.txt ???''''' ver

#ver se ha impossible values

In [20]:
dataset = pd.read_csv(r'../data/customer_info.csv',index_col=0)

In [21]:
print(dataset.shape)
dataset.head()

(33038, 24)

,customer_name,customer_gender,customer_birthdate,kids_home,teens_home,number_complaints,distinct_stores_visited,lifetime_spend_groceries,lifetime_spend_electronics,typical_hour,...,lifetime_spend_fish,lifetime_spend_hygiene,lifetime_spend_videogames,lifetime_spend_petfood,lifetime_total_distinct_products,percentage_of_products_bought_promotion,year_first_transaction,loyalty_card_number,latitude,longitude
customer_id,,,,,,,,,,,,,,,,,,,,,
3,Bsc. Crystal Kitchens,female,02/12/1970 01:36 PM,1.0,1.0,1.0,3.0,11731.0,4553.0,NaN,...,213.0,552.0,256.0,384.0,189.0,0.631599,2020.0,1.0,38.794428,-9.215739
4,Bsc. Glenda Bauman,female,11/13/1975 06:58 PM,1.0,0.0,0.0,2.0,13694.0,963.0,NaN,...,15.0,1880.0,333.0,665.0,130.0,0.149890,2013.0,1.0,38.751711,-9.179611
5,Msc. Antonio Campbell,male,09/10/1971 10:07 AM,0.0,0.0,NaN,2.0,12407.0,0.0,11.0,...,273.0,507.0,101.0,222.0,81.0,0.069126,2005.0,NaN,38.780678,-9.160656
7,John Kelling,male,10/23/1982 11:20 AM,0.0,0.0,2.0,1.0,7493.0,1105.0,18.0,...,1083.0,485.0,1656.0,184.0,92.0,0.253609,2021.0,1.0,38.739548,-9.148679
8,Arthur Dematteo,male,08/04/1969 10:22 PM,0.0,0.0,3.0,1.0,9187.0,10841.0,17.0,...,1015.0,297.0,1258.0,441.0,6.0,0.186569,2021.0,1.0,38.733071,-9.188188

### **Checking Impossible Values**

# age >0
# kids_home teens_home number_complaints distincts> 0 e nao pode ser decimal
# lifetime spend.... >0
# typical hour 6 < hour < 24
#percenteage < 100 >0
# year first transaction menor q o ano atual 
# latitude -90 e 90 longitude -180 e 180
# age >0

In [22]:
dataset['typical_hour'].value_counts()

typical_hour
8.0     4184
14.0    3459
7.0     2663
9.0     2453
10.0    2332
11.0    2277
12.0    1850
6.0     1731
13.0    1559
23.0    1280
15.0    1267
16.0    1174
17.0    1145
18.0    1125
19.0    1072
20.0    1011
21.0     985
22.0     810
Name: count, dtype: int64

In [23]:
df_teste = handle_datatypes(dataset)
df_teste = check_impossible_values(df_teste)

# Vê quem é que está 100% vazio
print(df_teste.isna().sum())

c:\Users\laura\Desktop\ML II\ml_project\notebooks\../src\datacleaning.py:12: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dataset['customer_birthdate'] = pd.to_datetime(dataset['customer_birthdate'], errors='coerce', dayfirst=True)

customer_name                                  0
customer_gender                                0
kids_home                                    330
teens_home                                   330
number_complaints                            661
distinct_stores_visited                      330
lifetime_spend_groceries                       0
lifetime_spend_electronics                   661
typical_hour                               33038
lifetime_spend_vegetables                    661
lifetime_spend_nonalcohol_drinks               0
lifetime_spend_alcohol_drinks                330
lifetime_spend_meat                          661
lifetime_spend_fish                          991
lifetime_spend_hygiene                       330
lifetime_spend_videogames                    661
lifetime_spend_petfood                       661
lifetime_total_distinct_products               0
percentage_of_products_bought_promotion     2085
year_first_transaction                         0
loyalty_card_number                        13106
latitude                                       0
longitude                                      0
customer_age                                 165
dtype: int64

In [6]:
clean_df = clean_data(dataset)

c:\Users\laura\Desktop\ML II\ml_project\notebooks\../src\datacleaning.py:12: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dataset['customer_birthdate'] = pd.to_datetime(dataset['customer_birthdate'], errors='coerce', dayfirst=True)
c:\Users\laura\anaconda3\envs\ML\Lib\site-packages\sklearn\utils\extmath.py:1144: RuntimeWarning: invalid value encountered in divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
c:\Users\laura\anaconda3\envs\ML\Lib\site-packages\sklearn\utils\extmath.py:1149: RuntimeWarning: invalid value encountered in divide
  T = new_sum / new_sample_count
c:\Users\laura\anaconda3\envs\ML\Lib\site-packages\sklearn\utils\extmath.py:1169: RuntimeWarning: invalid value encountered in divide
  new_unnormalized_variance -= correction**2 / new_sample_count

ValueError: operands could not be broadcast together with shapes (33038,21) (22,) (33038,21)

In [ ]:
dataset.isnull().sum()

customer_name                                  0
customer_gender                                0
customer_birthdate                           165
kids_home                                    330
teens_home                                   330
number_complaints                            661
distinct_stores_visited                      330
lifetime_spend_groceries                       0
lifetime_spend_electronics                   661
typical_hour                                 661
lifetime_spend_vegetables                    661
lifetime_spend_nonalcohol_drinks               0
lifetime_spend_alcohol_drinks                330
lifetime_spend_meat                          661
lifetime_spend_fish                          991
lifetime_spend_hygiene                       330
lifetime_spend_videogames                    661
lifetime_spend_petfood                       661
lifetime_total_distinct_products               0
percentage_of_products_bought_promotion      330
year_first_transaction                         0
loyalty_card_number                        13106
latitude                                       0
longitude                                      0
dtype: int64

### **Handling Data Types**

In [7]:
dataset.dtypes

customer_name                               object
customer_gender                             object
customer_birthdate                          object
kids_home                                  float64
teens_home                                 float64
number_complaints                          float64
distinct_stores_visited                    float64
lifetime_spend_groceries                   float64
lifetime_spend_electronics                 float64
typical_hour                               float64
lifetime_spend_vegetables                  float64
lifetime_spend_nonalcohol_drinks           float64
lifetime_spend_alcohol_drinks              float64
lifetime_spend_meat                        float64
lifetime_spend_fish                        float64
lifetime_spend_hygiene                     float64
lifetime_spend_videogames                  float64
lifetime_spend_petfood                     float64
lifetime_total_distinct_products           float64
percentage_of_products_bought_promotion    float64
year_first_transaction                     float64
loyalty_card_number                        float64
latitude                                   float64
longitude                                  float64
dtype: object

### **Drop duplicates**

In [8]:
dataset.drop_duplicates()

,customer_name,customer_gender,customer_birthdate,kids_home,teens_home,number_complaints,distinct_stores_visited,lifetime_spend_groceries,lifetime_spend_electronics,typical_hour,...,lifetime_spend_fish,lifetime_spend_hygiene,lifetime_spend_videogames,lifetime_spend_petfood,lifetime_total_distinct_products,percentage_of_products_bought_promotion,year_first_transaction,loyalty_card_number,latitude,longitude
customer_id,,,,,,,,,,,,,,,,,,,,,
3,Bsc. Crystal Kitchens,female,02/12/1970 01:36 PM,1.0,1.0,1.0,3.0,11731.0,4553.0,NaN,...,213.0,552.0,256.0,384.0,189.0,0.631599,2020.0,1.0,38.794428,-9.215739
4,Bsc. Glenda Bauman,female,11/13/1975 06:58 PM,1.0,0.0,0.0,2.0,13694.0,963.0,NaN,...,15.0,1880.0,333.0,665.0,130.0,0.149890,2013.0,1.0,38.751711,-9.179611
5,Msc. Antonio Campbell,male,09/10/1971 10:07 AM,0.0,0.0,NaN,2.0,12407.0,0.0,11.0,...,273.0,507.0,101.0,222.0,81.0,0.069126,2005.0,NaN,38.780678,-9.160656
7,John Kelling,male,10/23/1982 11:20 AM,0.0,0.0,2.0,1.0,7493.0,1105.0,18.0,...,1083.0,485.0,1656.0,184.0,92.0,0.253609,2021.0,1.0,38.739548,-9.148679
8,Arthur Dematteo,male,08/04/1969 10:22 PM,0.0,0.0,3.0,1.0,9187.0,10841.0,17.0,...,1015.0,297.0,1258.0,441.0,6.0,0.186569,2021.0,1.0,38.733071,-9.188188
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39996,Joshua Howard,male,05/16/1973 02:04 PM,0.0,0.0,2.0,1.0,475.0,13488.0,NaN,...,1154.0,62.0,1598.0,366.0,162.0,0.261352,2014.0,NaN,38.742306,-9.163971
39997,Anthony Hines,male,05/10/1955 01:19 AM,1.0,0.0,1.0,1.0,8430.0,14408.0,21.0,...,602.0,220.0,2105.0,227.0,97.0,0.143479,2014.0,NaN,38.748505,-9.193445
39998,Edna Hasselman,female,05/15/1945 11:09 PM,1.0,1.0,0.0,4.0,8029.0,1480.0,14.0,...,NaN,1719.0,89.0,258.0,206.0,0.181917,2012.0,NaN,38.776003,-9.137943
39999,George Kramer,male,05/25/1951 09:02 PM,1.0,1.0,1.0,6.0,8364.0,3114.0,11.0,...,113.0,410.0,NaN,225.0,385.0,0.807259,2017.0,NaN,38.736034,-9.145235
40000,Sammie Wright,female,07/09/1990 10:27 AM,0.0,1.0,1.0,1.0,4774.0,2127.0,7.0,...,729.0,1331.0,323.0,239.0,102.0,0.252563,2017.0,NaN,38.758936,-9.145988

In [9]:
dataset['typical_hour'].value_counts()

typical_hour
8.0     4184
14.0    3459
7.0     2663
9.0     2453
10.0    2332
11.0    2277
12.0    1850
6.0     1731
13.0    1559
23.0    1280
15.0    1267
16.0    1174
17.0    1145
18.0    1125
19.0    1072
20.0    1011
21.0     985
22.0     810
Name: count, dtype: int64

### **Handling Missing Values**

In [10]:
dataset.isnull().sum()

customer_name                                  0
customer_gender                                0
customer_birthdate                           165
kids_home                                    330
teens_home                                   330
number_complaints                            661
distinct_stores_visited                      330
lifetime_spend_groceries                       0
lifetime_spend_electronics                   661
typical_hour                                 661
lifetime_spend_vegetables                    661
lifetime_spend_nonalcohol_drinks               0
lifetime_spend_alcohol_drinks                330
lifetime_spend_meat                          661
lifetime_spend_fish                          991
lifetime_spend_hygiene                       330
lifetime_spend_videogames                    661
lifetime_spend_petfood                       661
lifetime_total_distinct_products               0
percentage_of_products_bought_promotion      330
year_first_transaction                         0
loyalty_card_number                        13106
latitude                                       0
longitude                                      0
dtype: int64

In [11]:
dataset.head(10)

,customer_name,customer_gender,customer_birthdate,kids_home,teens_home,number_complaints,distinct_stores_visited,lifetime_spend_groceries,lifetime_spend_electronics,typical_hour,...,lifetime_spend_fish,lifetime_spend_hygiene,lifetime_spend_videogames,lifetime_spend_petfood,lifetime_total_distinct_products,percentage_of_products_bought_promotion,year_first_transaction,loyalty_card_number,latitude,longitude
customer_id,,,,,,,,,,,,,,,,,,,,,
3,Bsc. Crystal Kitchens,female,02/12/1970 01:36 PM,1.0,1.0,1.0,3.0,11731.0,4553.0,NaN,...,213.0,552.0,256.0,384.0,189.0,0.631599,2020.0,1.0,38.794428,-9.215739
4,Bsc. Glenda Bauman,female,11/13/1975 06:58 PM,1.0,0.0,0.0,2.0,13694.0,963.0,NaN,...,15.0,1880.0,333.0,665.0,130.0,0.149890,2013.0,1.0,38.751711,-9.179611
5,Msc. Antonio Campbell,male,09/10/1971 10:07 AM,0.0,0.0,NaN,2.0,12407.0,0.0,11.0,...,273.0,507.0,101.0,222.0,81.0,0.069126,2005.0,NaN,38.780678,-9.160656
7,John Kelling,male,10/23/1982 11:20 AM,0.0,0.0,2.0,1.0,7493.0,1105.0,18.0,...,1083.0,485.0,1656.0,184.0,92.0,0.253609,2021.0,1.0,38.739548,-9.148679
8,Arthur Dematteo,male,08/04/1969 10:22 PM,0.0,0.0,3.0,1.0,9187.0,10841.0,17.0,...,1015.0,297.0,1258.0,441.0,6.0,0.186569,2021.0,1.0,38.733071,-9.188188
9,Msc. Nadine Garcia,female,10/09/1968 04:01 AM,1.0,1.0,1.0,6.0,16530.0,1156.0,6.0,...,76.0,513.0,225.0,NaN,84.0,0.150646,2011.0,1.0,38.735577,-9.172423
10,Phd. Franklin Alba,male,06/09/1971 05:08 AM,2.0,1.0,0.0,1.0,22240.0,NaN,9.0,...,1723.0,886.0,203.0,119.0,202.0,0.275412,2014.0,1.0,38.730322,-9.144022
11,Bsc. Robert Hansing,male,07/19/1977 10:22 AM,1.0,1.0,1.0,6.0,29765.0,1543.0,10.0,...,731.0,1240.0,1849.0,397.0,180.0,0.164251,2017.0,1.0,38.739328,-9.225047
12,Phd. Dorothy Pacheco,female,05/19/2000 03:02 AM,0.0,0.0,0.0,2.0,9281.0,254.0,18.0,...,598.0,673.0,71.0,64.0,29.0,-0.131176,2018.0,NaN,38.748616,-9.167756
14,Msc. Arron Burgener,male,11/28/1948 07:53 PM,1.0,0.0,1.0,3.0,7981.0,2151.0,12.0,...,24.0,1393.0,178.0,90.0,57.0,0.197353,2017.0,1.0,38.788819,-9.184158

In [11]:
clean_df.isnull().sum()

customer_name                              0
customer_gender                            0
kids_home                                  0
teens_home                                 0
number_complaints                          0
distinct_stores_visited                    0
lifetime_spend_groceries                   0
lifetime_spend_electronics                 0
typical_hour                               0
lifetime_spend_vegetables                  0
lifetime_spend_nonalcohol_drinks           0
lifetime_spend_alcohol_drinks              0
lifetime_spend_meat                        0
lifetime_spend_fish                        0
lifetime_spend_hygiene                     0
lifetime_spend_videogames                  0
lifetime_spend_petfood                     0
lifetime_total_distinct_products           0
percentage_of_products_bought_promotion    0
year_first_transaction                     0
loyalty_card_number                        0
latitude                                   0
longitude                                  0
customer_age                               0
dtype: int64

In [13]:
clean_df['kids_home'].value_counts()

kids_home
1    16208
0     9276
2     4955
3     1102
4      663
5      433
6      243
7      106
8       52
Name: count, dtype: Int64

In [ ]:
clean_data = c

In [13]:
dataset['number_complaints'].value_counts()
dataset['distinct_stores_visited'].value_counts()
dataset[dataset['lifetime_spend_alcohol_drinks'] < 0]
dataset[dataset['lifetime_spend_electronics' ] < 0]
dataset[dataset['lifetime_spend_groceries'] < 0]
dataset[dataset['lifetime_spend_home_furnishing'] < 0]

KeyError: 'lifetime_spend_home_furnishing'

In [ ]:
dataset[dataset['customer_birthdate'].isnull()]

#conditional imputation

,customer_name,customer_gender,customer_birthdate,kids_home,teens_home,number_complaints,distinct_stores_visited,lifetime_spend_groceries,lifetime_spend_electronics,typical_hour,...,lifetime_spend_fish,lifetime_spend_hygiene,lifetime_spend_videogames,lifetime_spend_petfood,lifetime_total_distinct_products,percentage_of_products_bought_promotion,year_first_transaction,loyalty_card_number,latitude,longitude
customer_id,,,,,,,,,,,,,,,,,,,,,
401,Msc. Robert Zamora,male,NaN,NaN,0.0,1.0,5.0,1296.0,2377.0,15.0,...,514.0,233.0,319.0,17.0,351.0,0.542064,2016.0,1.0,38.763894,-9.197282
473,Bsc. Nikki Ali,female,NaN,6.0,4.0,1.0,4.0,9805.0,8372.0,11.0,...,1115.0,902.0,350.0,419.0,327.0,0.171643,2029.0,1.0,38.724110,-9.166377
526,Bsc. Theodore Hernandez,male,NaN,1.0,1.0,1.0,5.0,3029.0,898.0,16.0,...,1.0,2004.0,215.0,317.0,76.0,0.022600,2017.0,1.0,38.754457,-9.154369
580,Phd. Steve Ligon,male,NaN,2.0,1.0,3.0,5.0,41315.0,6651.0,12.0,...,1180.0,1188.0,325.0,231.0,248.0,0.151446,2012.0,1.0,38.720267,-9.117971
863,Phd. Sergio Johnson,male,NaN,0.0,1.0,0.0,3.0,16163.0,413.0,15.0,...,70.0,1738.0,194.0,212.0,86.0,0.259576,2014.0,1.0,38.735848,-9.153364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39012,Suzanne Harmon,female,NaN,4.0,1.0,1.0,1.0,21153.0,6179.0,12.0,...,300.0,996.0,400.0,415.0,285.0,0.107332,2005.0,NaN,38.746545,-9.142421
39413,Thomas Bowman,male,NaN,1.0,1.0,0.0,3.0,1042.0,2286.0,8.0,...,24.0,391.0,231.0,98.0,59.0,0.093210,2020.0,NaN,38.734696,-9.119887
39595,Bettye Murphy,female,NaN,1.0,2.0,1.0,1.0,20234.0,280.0,8.0,...,380.0,864.0,110.0,290.0,124.0,-0.022088,2012.0,NaN,38.766244,-9.159973
39857,Donald Wylie,male,NaN,0.0,0.0,1.0,5.0,10790.0,43.0,17.0,...,300.0,308.0,NaN,260.0,22.0,0.017567,2029.0,NaN,38.750542,-9.151325
39881,Chet Burns,male,NaN,0.0,0.0,0.0,2.0,11486.0,229.0,23.0,...,900.0,34.0,185.0,170.0,15.0,-0.318683,2029.0,NaN,38.734491,-9.158304

In [ ]:
#customer birthdate

In [ ]:
#kids home

In [ ]:
#teens home

In [ ]:

dataset['number_complaints'].unique()

array([ 1.,  0., nan,  2.,  3.,  5.,  6.,  4.,  7.])